config/routes.rb
Rails.application.routes.draw do

  resources :clients
  resources :services
  resources :order_services
  resources :parts

  root 'homes#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

	has_many :order_services
	has_many :services, through: :order_services
  has_many :parts, through: :order_services
	
end

app/models/order_service.rb
class OrderService < ActiveRecord::Base

	belongs_to :client
	has_and_belongs_to_many :services, :dependent => :destroy
	has_and_belongs_to_many :parts, :dependent => :destroy

	accepts_nested_attributes_for :services
	accepts_nested_attributes_for :parts
	
end

app/models/part.rb
class Part < ActiveRecord::Base
	
	has_and_belongs_to_many :order_services 
	
end

app/models/service.rb
class Service < ActiveRecord::Base

	
	has_and_belongs_to_many :order_services	

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_action :set_client, only: [:show, :edit, :update, :destroy]


	def index
		@clients = Client.all
		
	end
		
	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)

		respond_to do |format|
	      if @client.save
	        format.html { redirect_to @client, notice: 'Registro criado com sucesso' }
	        format.json { render :show, status: :created, location: @client }
	      else
	        format.html { render :new }
	        format.json { render json: @client.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Registro atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@client.destroy
  	respond_to do |format|
  		format.html {redirect_to clients_url, notice: 'Registro excluido com sucesso'}
  	end
  end

	
private
	
	def set_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:nome, :endereco, :bairro, :cidade, :uf, :cep, :email, :tel)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
	end
end

app/controllers/order_services_controller.rb
class OrderServicesController < ApplicationController

	before_action :set_order_service, only: [:show, :edit, :update, :destroy]

	def index
		@order_services = OrderService.all

	end

	def new
		@order_service = OrderService.new


	end

	def create
	
		@order_service = OrderService.new(order_service_params)
		@p_service = @order_service.parts
				
		respond_to do |format|
	      if @order_service.save
	        format.html { redirect_to @order_service, notice: 'Registro criado com sucesso' }
	        format.json { render :show, status: :created, location: @order_service }
	      else
	        format.html { render :new }
	        format.json { render json: @order_service.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def update
	  respond_to do |format|
      if @order_service.update(order_service_params)
        format.html { redirect_to @order_service, notice: 'Registro atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @order_service }
      else
        format.html { render :edit }
        format.json { render json: @order_service.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@order_service.destroy
  		respond_to do |format|
  			format.html {redirect_to order_services_url, notice: 'Registro excluido com sucesso'}
  		end
	end

	private

	def set_order_service
		@order_service = OrderService.find(params[:id])

	end

	def order_service_params
		params.require(:order_service).permit(:client_id, :date, {:service_ids => []}, {:part_ids => []})
	end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

	before_action :set_part, only: [:show, :edit, :update, :destroy]

	def index
		@parts = Part.all
	end

	def new
		@part = Part.new
	end

	def create 
		@part = Part.new(part_params)

		respond_to do |format|
	      if @part.save
	        format.html { redirect_to @part, notice: 'Registro criado com sucesso' }
	        format.json { render :show, status: :created, location: @part }
	      else
	        format.html { render :new }
	        format.json { render json: @part.errors, status: :unprocessable_entity }
	      end
	    end
	end


	private

	def set_part
		@part = Part.find(params[:id])
	end

	def part_params
		params.require(:part).permit(:descricao, :modelo, :p_compra, :p_venda, :quantidade, :lucro)
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	before_action :set_service, only: [:show, :edit, :update, :destroy]

	def index
		@services = Service.all
	end

	def new
		@service = Service.new
	end
	def show
	end

	def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Registro atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

	def create
		@service = Service.new(service_params)

		respond_to do |format|
	      if @service.save
	        format.html { redirect_to @service, notice: 'Registro criado com sucesso' }
	        format.json { render :show, status: :created, location: @service }
	      else
	        format.html { render :new }
	        format.json { render json: @service.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
		@service.destroy
  		respond_to do |format|
  			format.html {redirect_to services_url, notice: 'Registro excluido com sucesso'}
  		end
	end
	private
	
	def set_service
		@service = Service.find(params[:id])
	end

	def service_params
		params.require(:service).permit(:descricao, :valor, {:parts_ids => []})
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_service_services_helper.rb
module OrderServiceServicesHelper
end

app/helpers/order_services__helper.rb
module OrderServicesHelper
end

app/helpers/order_services_helper.rb
module OrderServicesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tformulario"> 
    <%= f.label :Nome%> <br>
    <%= f.text_field :nome , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Endereço%> <br>
    <%= f.text_field :endereco , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Bairro%> <br>
    <%= f.text_field :bairro , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Cidade%> <br>
    <%= f.text_field :cidade , :size=>100%>
  </div>
  <div class="tformulario"> 
    <%= f.label :UF%> <br>
    <%= f.text_field :uf , :size=>5%>
  </div>
  <div class="tformulario"> 
    <%= f.label :Cep%> <br>
    <%= f.text_field :cep , :size=>30%>
  </div>
  <div class="tformulario"> 
    <%= f.label :Email%> <br>
    <%= f.text_field :email , :size=>50%>
  </div>
  <div class="tformulario"> 
    <%= f.label :Tel%> <br>
    <%= f.text_field :tel , :size=>40%>
  </div>
  <div>
    <br>
    <%=f.submit "Salvar"%>
  </div>
<%end%>

app/views/clients/edit.html.erb
<h3 class="texto">Edição de Registro</h3>
<%= render 'form' %>

app/views/clients/index.html.erb
<h3 class="texto"> Listagem de Clientes Cadastrados </h3>

<table class="show">
  <thead>
    <tr >
      <th>Nome</th>
      <th>Endereco</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Uf</th>
      <th>Cep</th>
      <th>Tel</th>
      <th colspan="3">Opções</th>
    </tr>

  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nome %></td>
        <td><%= client.endereco %></td>
        <td><%= client.bairro %></td>
        <td><%= client.cidade %></td>
        <td><%= client.uf %></td>
        <td><%= client.cep %></td>
        <td><%= client.tel %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

app/views/clients/new.html.erb
<h3 class="texto">Cadastro de Clientes</h3>
<%= render 'form' %>

app/views/clients/show.html.erb
<h3 class="texto"> Visualização de Cliente </h3>

<p class="texto" align="center"><%= notice %></p>

<p class="tformulario">
  <strong>Nome:</strong>
  <%= @client.nome %>
</p>

<p class="tformulario">
  <strong>Endereco:</strong>
  <%= @client.endereco %>
</p>

<p class="tformulario">
  <strong>Bairro:</strong>
  <%= @client.bairro %>
</p>

<p class="tformulario">
  <strong>Cidade:</strong>
  <%= @client.cidade %>
</p>

<p class="tformulario">
  <strong>Uf:</strong>
  <%= @client.uf %>
</p>

<p class="tformulario">
  <strong>Cep:</strong>
  <%= @client.cep %>
</p>

<p class="tformulario">
  <strong>Tel:</strong>
  <%= @client.tel %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', root_path, confirm: 'Tem certeza que deseja voltar?'%>

app/views/homes/index.html.erb
  <img src="../images/fundo.jpg" alt="teste" class="fundo">
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckUP - Micros</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topo"> 
  <img src="/images/logo.jpg" alt="teste" class="logo"></img>
<font class="texto">  </font>
</div>

<div class="corpo">
<div id='cssmenu'>
<ul>
   <li class='active'><%= link_to  'Home' , root_path%> </li>
   <li class='has-sub'><a href='#'><span>Cadastro</span></a>
      <ul>
         <li><%= link_to  'Clientes' , new_client_path%></a></li>
         <li><%= link_to  'Serviços' , new_service_path%></a></li>
         <li><%= link_to  'Peças' , new_part_path%></li>
         <li><%= link_to  'Ordem de serviços' , new_order_service_path%></a></li>.
      </ul>
   </li>
   <li class='has-sub'><a href='#'><span>Consultas</span></a>
      <ul>
         <li><%= link_to 'Clientes' , clients_path%></li>
         <li><%= link_to 'Serviços' , services_path%></li>
         <li><%= link_to 'Peças' , parts_path%> </li>
         <li><%= link_to 'Ordem de serviços' , order_services_path%></a></li>
      </ul>
   </li>
   <li class='has-sub last'><a href='#'><span>Relatórios</span></a>
      <ul>
         <li><a href='#'><span>Cliente</span></a></li>
         <li><a href='#'><span>Serviços</span></a></li>
         <li><a href='#'><span>Peças</span></a></li>
		 <li><a href='Orcamento.html'><span>Orçamento</span></a></li>
         <li class='last'><a href='#'><span>Fechamento</span></a></li>
      </ul>
   </li>
   <li class='has-sub last'><a href='#'><span>Agenda</span></a>
     
   </li>
</ul>
</div>
<div class="formulario" >
 
  <%= yield %>


</div>

</body>
</html>

app/views/order_services/_form.html.erb
<%= form_for(@order_service) do |f| %>
  <% if @order_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_service.errors.count, "error") %> prohibited this order service from being saved:</h2>
      <ul>
      <% @order_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tformulario"> 
    <%= f.label :cliente %> <br>
    <%= f.select :client_id, 
                 Client.all.collect {|p| [ p.nome.capitalize, p.id ] },
                 {include_blank: 'Escolha um Cliente'} %>    
  </div>
  <br>
  <div class="tformulario"> 
    <%= f.label :serviço %> <br>
    <%= f.collection_check_boxes(:service_ids, Service.all, :id, :descricao)%>          
  </div>  
  <br>

   <div class="tformulario">     
      <%= f.label :peça %> <br>
      <%= f.collection_check_boxes(:part_ids, Part.all, :id, :descricao)%>    
  </div> 
  <br>
  <div class="tformulario">
    <%= f.label :Data %>  <br>
    <%= f.text_field :date , :type => "date"%>
  </div>
  
  <div>
    <br>
    <%=f.submit "Salvar"%>
  </div>
<%end%>

app/views/order_services/edit.html.erb
<h3 class="texto">Edição de Registro</h3>
<%= render 'form' %>

app/views/order_services/index.html.erb
<h3 class="texto"> Listagem de Ordem de Serviços Cadastrados</h3>

<table class="show">
  <thead>
    <tr >
      <th>Cliente</th>      
      <th>Data</th>      
      <th colspan="3">Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @order_services.each do |serv| %>
      <tr>
        <td><%= serv.client_id %></td>           
        <td><%= serv.date %></td>        
        <td><%= link_to 'Show', serv%></td>
        <td><%= link_to 'Edit', edit_order_service_path(serv) %></td>
        <td><%= link_to 'Destroy', serv, method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

app/views/order_services/new.html.erb
<h3 class="texto">Cadastro de Ordem de Serviço</h3>
<%= render 'form' %>

app/views/order_services/show.html.erb
<h3 class="texto"> Visualização de Ordem de Serviço </h3>

<p class="texto" align="center"><%= notice %></p>

<p class="tformulario">
  <strong>Cliente:</strong>
  <%= @order_service.client_id %>
</p>


<p class="tformulario">
  <strong>Data:</strong>
  <%= @order_service.date %>
</p>

<%= link_to 'Edit', edit_order_service_path(@order_service) %> |
<%= link_to 'Back', root_path, confirm: 'Tem certeza que deseja voltar?'%>

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>
      <ul>
      <% @part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tformulario"> 
    <%= f.label :Descrição%> <br>
    <%= f.text_field :descricao , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Modelo%> <br>
    <%= f.text_field :modelo , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Preço_de_Compra%> <br>
    <%= f.text_field :p_compra , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Preço_de_Venda%> <br>
    <%= f.text_field :p_venda , :size=>100%>
  </div>
  <div class="tformulario"> 
    <%= f.label :Quantidade%> <br>
    <%= f.text_field :quantidade , :size=>5, :type=>"number"%>
  </div>
  <div class="tformulario"> 
    <%= f.label :Lucro%> <br>
    <%= f.text_field :lucro , :size=>30%>
  </div>
  
  <div>
    <br>
    <%=f.submit "Salvar"%>
  </div>
<%end%>

app/views/parts/edit.html.erb
edit.html.erb

app/views/parts/index.html.erb
<h3 class="texto"> Listagem de Peças Cadastradas</h3>

<table class="show">
  <thead>
    <tr >
      <th>Descrição</th>
      <th>Modelo</th>      
      <th>Preço de Compra</th>
      <th>Preço de Venda</th>
      <th>Quantidade</th>
      <th>Lucro</th>
      <th colspan="3">Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |p| %>
      <tr>
        <td><%= p.descricao %></td>
        <td><%= p.modelo %></td>
        <td><%= p.p_compra %></td>
        <td><%= p.p_venda %></td>
        <td><%= p.quantidade %></td>
        <td><%= p.lucro %></td>
        
        <td><%= link_to 'Show', p%></td>
        <td><%= link_to 'Edit', edit_part_path(p) %></td>
        <td><%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

app/views/parts/new.html.erb
<h3 class="texto">Cadastro de Peças</h3>
<%= render 'form' %>

app/views/parts/show.html.erb
show.html.erb

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tformulario"> 
    <%= f.label :Descrição%> <br>
    <%= f.text_field :descricao , :size=>100 %>
  </div>
  <div class="tformulario"> 
    <%= f.label :Valor%> <br>
    <%= f.text_field :valor , :size=>100 %>
  </div>  
  <div>
    <br>
    <%=f.submit "Salvar"%>
  </div>
<%end%>

app/views/services/edit.html.erb
<h3 class="texto">Edição de Registro</h3>
<%= render 'form' %>

app/views/services/index.html.erb
<h3 class="texto"> Listagem de Serviços Cadastrados</h3>

<table class="show">
  <thead>
    <tr >
      <th>Descrição</th>
      <th>Valor</th>      
      <th colspan="3">Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |serv| %>
      <tr>
        <td><%= serv.descricao %></td>
        <td><%= serv.valor %></td>        
        <td><%= link_to 'Show', serv%></td>
        <td><%= link_to 'Edit', edit_service_path(serv) %></td>
        <td><%= link_to 'Destroy', serv, method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

app/views/services/new.html.erb
<h3 class="texto">Cadastro de Serviços</h3>
<%= render 'form' %>

app/views/services/show.html.erb
<h3 class="texto"> Visualização de Serviço </h3>

<p class="texto" align="center"><%= notice %></p>

<p class="tformulario">
  <strong>Descrição:</strong>
  <%= @service.descricao %>
</p>

<p class="tformulario">
  <strong>Valor:</strong>
  <%= @service.valor %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', root_path, confirm: 'Tem certeza que deseja voltar?'%>